### ISSUE TITLE
[macOS arm64] Bug: `Failed to compile shader:`

### ISSUE THREAD

**Issue by qwertychouskie** [SpaiR/imgui-java#275]
### Version

1.86.12

### What happened?

```
java.lang.IllegalStateException: Failed to compile shader:
    at imgui.gl3.ImGuiImplGl3.createAndCompileShader(ImGuiImplGl3.java:463)
    at imgui.gl3.ImGuiImplGl3.createShaders(ImGuiImplGl3.java:313)
    at imgui.gl3.ImGuiImplGl3.createDeviceObjects(ImGuiImplGl3.java:272)
    at imgui.gl3.ImGuiImplGl3.init(ImGuiImplGl3.java:127)
    at io.github.deltacv.papervision.platform.lwjgl.EventLoopWindow.init(EventLoopWindow.java:58)
    at io.github.deltacv.papervision.platform.lwjgl.PaperVisionApp.start(PaperVisionApp.kt:38)
    at io.github.deltacv.papervision.plugin.EOCVSimIpcPaperVisionMain.call(EOCVSimIpcPaperVisionMain.java:67)
    at io.github.deltacv.papervision.plugin.EOCVSimIpcPaperVisionMain.call(EOCVSimIpcPaperVisionMain.java:21)
    at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
    at picocli.CommandLine.access$1500(CommandLine.java:148)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
    at picocli.CommandLine.execute(CommandLine.java:2174)
    at io.github.deltacv.papervision.plugin.EOCVSimIpcPaperVisionMain.main(EOCVSimIpcPaperVisionMain.java:105)
```

### Reproduction

It happens upon trying to load the [PaperVision](https://github.com/deltacv/PaperVision) window.  The version of PaperVision used can be downloaded [here](https://www.dropbox.com/scl/fi/pa8ln57xdch1zuwkrsn4d/PaperVisionPlugin-1.0.0-dev-240926-0024-all.jar?rlkey=b63y5ybcky97g45p9kqro967b&st=n6yziy3l&dl=0).  You'll also need [the development version of EOCV-Sim](https://github.com/deltacv/EOCV-Sim/releases/tag/Dev).

**Comment by SpaiR** [comment]
There are many reasons why shaders might fail to compile, and in most cases, the issue lies with the end user's environment. For example, even in version 1.86.12, the shaders and their compilation paths are taken directly from the original repository, and personally, using macOS on arm64, I haven't experienced any issues.

I recommend trying the latest version of the binding. In version 1.87, I rewrote the OpenGL renderer, making its code structure as close to the original as possible. At the very least, any shader compilation error message in this version should provide more detailed information about the cause.

Until then, it's difficult to say anything more specific about your error, as the log contains no details about what exactly failed inside the shader...

**Comment by qwertychouskie** [comment]
After updating to 1.87.5, the error is a bit different:
```
imgui.gl3.ImGuiImplGl3@479460a6: failed to compile vertex shader! With GLSL: #version 150
imgui.gl3.ImGuiImplGl3@479460a6: failed to compile fragment shader! With GLSL: #version 150
imgui.gl3.ImGuiImplGl3@479460a6: failed to link shader program! With GLSL: #version 150
[LWJGL] GLFW_FEATURE_UNAVAILABLE error
	Description : Cocoa: Regular windows do not have icons on macOS
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:2435)
		org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:2467)
		io.github.deltacv.papervision.platform.lwjgl.glfw.GlfwWindow.setIcon(GlfwWindow.kt:30)
		io.github.deltacv.papervision.PaperVision.firstProcess(PaperVision.kt:169)
		io.github.deltacv.papervision.platform.lwjgl.PaperVisionApp.process(PaperVisionApp.kt:56)
		io.github.deltacv.papervision.platform.lwjgl.EventLoopWindow.runFrame(EventLoopWindow.java:173)
		io.github.deltacv.papervision.platform.lwjgl.EventLoopWindow.run(EventLoopWindow.java:159)
		io.github.deltacv.papervision.platform.lwjgl.PaperVisionApp.start(PaperVisionApp.kt:39)
		io.github.deltacv.papervision.plugin.EOCVSimIpcPaperVisionMain.call(EOCVSimIpcPaperVisionMain.java:67)
		io.github.deltacv.papervision.plugin.EOCVSimIpcPaperVisionMain.call(EOCVSimIpcPaperVisionMain.java:21)
		picocli.CommandLine.executeUserObject(CommandLine.java:2045)
		picocli.CommandLine.access$1500(CommandLine.java:148)
		picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
		picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
		picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
		picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
		picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
		picocli.CommandLine.execute(CommandLine.java:2174)
		io.github.deltacv.papervision.plugin.EOCVSimIpcPaperVisionMain.main(EOCVSimIpcPaperVisionMain.java:105)
```

**Comment by SpaiR** [comment]
The errors only confirm that the issue is on your side, and I can't assist with that. However, I can suggest that the problem is likely related to your general OpenGL configuration—usually, something like an unconfigured context or a similar issue.

Start by trying to run the `Application` module and see if it works. If it does, compare your code with the application template and check for any differences. If it doesn't work and continues to throw errors, you'll need to investigate why your OpenGL shaders are failing to compile, as this appears to be the root of the problem.

It's possible the issue lies within `ImGuiImplGl3`, but the current error log provides no clues about where exactly the problem might be.

**Comment by qwertychouskie** [comment]
This issue is very strange.  We changed to use `imgui.app.Application` instead of a manual implementation (https://github.com/deltacv/PaperVision/commit/ebb1b413899a66660273d63724b72abb37825ab9), but we're still seeing the issue.
```
[17:48:36] [SLFJ4IOReceiver-out-2/INFO]: [PaperVisionProcessRunner] [main/INFO]: [PaperVision] PaperVision started
[17:48:36] [SLF4JIOReceiver-err-2/ERROR]: [PaperVisionProcessRunner] imgui.gl3.ImGuiImplGl3@51fadaff: failed to compile vertex shader! With GLSL: #version 150
[17:48:36] [SLF4JIOReceiver-err-2/ERROR]: [PaperVisionProcessRunner] imgui.gl3.ImGuiImplGl3@51fadaff: failed to compile fragment shader! With GLSL: #version 150
[17:48:36] [SLF4JIOReceiver-err-2/ERROR]: [PaperVisionProcessRunner] imgui.gl3.ImGuiImplGl3@51fadaff: failed to link shader program! With GLSL: #version 150
```
The window shows, but is blank:
![image](https://github.com/user-attachments/assets/787e799f-6972-4d5c-8843-2fa2c205f293)

Do you have any ideas or suggestions on how to debug this issue?  For reference, here's [the latest EOCV-Sim](https://github.com/deltacv/EOCV-Sim/releases/tag/v3.7.1) and here's [the latest Papervision](https://github.com/deltacv/PaperVision/releases/tag/Dev).

**Comment by qwertychouskie** [comment]
OK, it seems `-Djava.awt.headless=true` is absolutely critical on macOS.  You might want to document that somewhere, as it's really weird and obscure.
